### PR TITLE
Enabled LGTM and started fixing some of the code issues it unrooted

### PR DESCRIPTION
**Pull request by DX-MON**
[LGTM](https://lgtm.com) is a free code scanning service that looks for vulnerabilities and issues in the source of GitHub based projects. I have enabled this service for this repo (done from the LGTM site), which has provided this lovely list: https://lgtm.com/projects/g/fract4d/gnofract4d/?mode=list

This PR attempts to validly fix as many of these issues as is reasonable to improve code quality and provide a more solid baseline going forward. We can, if we so choose, also put a badge in the project README pointing at the project issue list, though I suspect as we do not currently show build status or code coverage, this is not something that's wanted, so I have not put anything like that in.

For now, opening as WIP as there are a lot of items to look at, evaluate and solve. For a first-time enable, however, the issue list is not that long given how large and complex the code base is.

### CODE REVIEW

**Comment by DX-MON** [comment]
I've put in a request (I think this has to be actioned by @edyoung) to enable LGTM on PRs.. I can't tell how well I'm really doing with this PR till that is enabled, but I think I hit so much code anyway that if this looks good, it should probably be reviewed and then merged and I can open another later to hit some more of the output we're getting

**Comment by edyoung** [comment]
I approved adding LGTM to the repo

**Review by edyoung — APPROVED** [review]

**Comment by DX-MON** [comment]
Ahh, this is frustrating but understandable.. to enable the service for PRs and such.. it takes a repo owner or admin going to https://lgtm.com/projects/g/fract4d/gnofract4d/ci/ with a LGTM account to actually enable it, meaning I can't.

**Comment by edyoung** [comment]
I think I have now enabled it. Sorry for the delay!

**Pull request merged**
