### PR TITLE
Use GitHub Actions instead of Travis

### PR DESCRIPTION
**Pull request by cjmayo**
With all the problems with Travis here is an attempt to use GitHub actions instead. Let's see if the PR works. One advantage - it is easier to re-run when there is a segfault...

It does clash with #141. So, would need to be updated.

### CODE REVIEW

**Comment by mindhells** [comment]
Never used them but looks great.
Maybe we could add the OS into the matrix and include macos as a supporting OS as well as ubuntu. I would rather use specific versions though: `ubuntu-18.04` and `macos-10.15`
Artifacts sound promising too for building binary releases with pyoxidizer (as @edyoung suggested in #133).

**Comment by cjmayo** [comment]
Added upload to Codecov (it can take the XML report from pytest-cov, unlike Coveralls).

Added a MacOS job for Python 3.7.

Being specific about OS versions would be my first idea, but here I'm not so sure, it creates maintenance work. On the other hand if we are saying we are supporting specific OS versions then that would be useful.

**Comment by DX-MON** [comment]
You can matrix on the OS versions as well as Python and have -latest and specific versions so you get to see if anything broke in the newest of the OS and set up support guarantees for the rest

**Comment by edyoung** [comment]
I'm all for it

**Comment by cjmayo** [comment]
Rebased on master to fix clashes and changed to specific OS's with the objective of trying everything at least once (will Ubuntu 20.04 work???).

**Comment by cjmayo** [comment]
> I'm all for it

Great! Can you enable Actions for the repository under Settings/Actions?

**Comment by edyoung** [comment]
Already enabled as as far as I can see

image

**Comment by cjmayo** [comment]
Thanks for checking. I have now pushed this PR as a branch to the repository and the actions started running. Also realised another commit was needed to stop trying to upload to Codecov from the Pylint job.

**Comment by edyoung** [comment]
Thanks! Looks great

**Comment by mindhells** [comment]
should .travis.yml file be removed?

**Comment by DX-MON** [comment]
Seeing we can re-create the config if we want to try fixing and re-enabling Travis at some later date, I see no harm in removing the file

**Pull request merged**
